### ISSUE TITLE
Method code too large exception

### ISSUE THREAD

**Issue by ZXTube** [ThexXTURBOXx/dex2jar#24]
Please fix the `Method code too large exception`. 

In this [Issue comment](https://github.com/pxb1988/dex2jar/issues/22#issuecomment-279476003) (Which is in the main dex2jar repository) the comment explained that this exception is not necessary at all and then explained how to edit the byte code so that this exception doesn't happen anymore.

Please make it so that this exception doesn't happen by default.

Thank you.

**Comment by ThexXTURBOXx** [comment]
I don't like fiddling around bytecode editing some jars we depend on since any version update will immediately break this.
However, maybe I am able to work around it differently by overwriting this function myself. I have not looked at the source code yet since I am very busy (and it is very late right now here).
But maybe I am able to play with this a bit in the next few days.
Also, another big problem I have with this approach: dex2jar also provides "recompiling" functionality and some users may complain afterwards anyway. But well... It's anyways better to support at least one-way conversion than no-way conversion :)

**Comment by ThexXTURBOXx** [comment]
I applied a similar workaround to the one in the linked comment in v53. Please see if it works for you, thanks!

**Comment by ZXTube** [comment]
Yes! Thank you it works now. Also thanks for answering quickly
