### ISSUE TITLE
Android projecr

### ISSUE THREAD

**Issue by moderGamer** [ThexXTURBOXx/dex2jar#39]
Hello, I want to use this project in my Android project, what libraries are needed, if possible, give me their names.

**Comment by ThexXTURBOXx** [comment]
Hello, if you are using dex2jar using jitpack.io, the necessary libraries are already incorporated automatically.
Otherwise, you can analyse the different gradle files for the subprojects in this repo or on Jitpack like this: https://jitpack.io/com/github/ThexXTURBOXx/dex2jar/dex-translator/v63/dex-translator-v63.pom
