### ISSUE TITLE
[question]Did you forget that you added a jar called ICU4J?

### ISSUE THREAD

**Issue by zhongqingsong** [ThexXTURBOXx/dex2jar#43]
I found that your release is much bigger than pxb1988's!! I compared it to the jar. And I find that you added a jar to your release called ICU4J, which is 10M+ and takes up quite a lot of file volume.
Then I searched your entire dex2jar code project, and I couldn't find a single reference to "com.ibm." Am I to assume that this ICU4J is not actually referenced in your code?
If so, I recommend removing the ICU4J to reduce the size of the file considerably. Your downloads will definitely increase.
Of course, if you do refer to this jar, I feel that your reference to this jar is not very good. Except for ICU4J, all the others add up to about 3M, and this one jar takes up 10M. This is a serious question.

**Comment by ThexXTURBOXx** [comment]
This is because on my fork, I updated all the dependencies to their respective newest versions.
One of these now use ICU4J as a dependency.
In BytecodeViewer, we have excluded this dependency from being shaded into the final jar since it did not seem to matter.
However, in order to avoid further issues, I decided to let it stay in the releases for now.

**Comment by ThexXTURBOXx** [comment]
After some more digging, I found https://github.com/gradle/gradle/issues/820 which mentions basically the same issue and a few attempts to fix it.
I have applied one of these workarounds and it seems to work fine now.
