### ISSUE TITLE
[advice] use SemVer, it's more standard

### ISSUE THREAD

**Issue by zhongqingsong** [ThexXTURBOXx/dex2jar#44]
From what I've observed, you like to use a generic version to manage releases, which creates a problem. It is this version of "vNum" that is not loved by programmers.
As programmers, we are more familiar with using the [SemVer]( https://semver.org/). Isn't that right?
So, I feel that release can also use this semantic version, with just a few minor changes. For example, **v73 -> 0.7.3**. It's simple, and it looks pretty standard.

**Comment by zhongqingsong** [comment]
Also, the file name of your release file should be adjusted as well. The system changes to dex-tools-SemVer.zip
(like dex-tools-0.7.3.zip)

This is more concise and easier to distinguish between files. Currently all your zip is the same name and to be honest sometimes I don't know which version I downloaded is the latest and I have to check the file modification time. It shouldn't be.

**Comment by ThexXTURBOXx** [comment]
To be honest, I thought about this quite a long time when I forked the project.
But it does not make sense in my eyes because I did not want to increment my dex2jar versions while the original project is still on a completely other version.
It just felt weird to use a completely different version than pxb1988.
And, to be honest, I don't really see a problem with the current approach. If someone understands "0.7.3", then he will also understand "v73" and vice versa. It is pretty much equivalent.
