### ISSUE TITLE
There are some error log about fastjson

### ISSUE THREAD

**Issue by RussiaVk** [ThexXTURBOXx/dex2jar#6]
There are some error log about fastjson
[haluo-error.zip](https://github.com/ThexXTURBOXx/dex2jar/files/7110083/haluo-error.zip)
apk file :https://wap.pp.cn/app/dl/fs08/2021/08/23/5/106_6b852528162327c9f056dd40f2ce9ce7.apk

**Comment by ThexXTURBOXx** [comment]
Thanks for reporting! I found the issue and fixed it accordingly.
I will reply here again as soon as the changes are online :)

The issue is in these lines:
```java
String elementTypeA = a.substring(as);
String elementTypeB = a.substring(bs);
```
As one can see, `elementTypeB` uses the String `a`, which is of course not what we want.
So, I've just changed it to `b` and your APK is decompiling perfectly fine for me now :)

**Comment by ThexXTURBOXx** [comment]
The new build is being deployed right now. `v25` should be available via [releases](https://github.com/ThexXTURBOXx/dex2jar/releases)
